---
- name: Common Prerequisites
  hosts: default
  become: true

  tasks:
  - name: Clean APT cache
    ansible.builtin.apt:
      clean: true

  - name: APT upgrade
    ansible.builtin.apt:
      update_cache: true
      upgrade: true

  - name: Install prerequisites
    ansible.builtin.apt:
      update_cache: true
      name:
        - net-tools
        - policycoreutils
        - ca-certificates

  - name: Tweak virtual memory 1/4
    ansible.posix.sysctl:
      name: vm.swappiness
      value: '30'

  - name: Tweak virtual memory 2/4
    ansible.posix.sysctl:
      name: vm.dirty_background_ratio
      value: '5'

  - name: Tweak virtual memory 3/4
    ansible.posix.sysctl:
      name: vm.dirty_ratio
      value: '60'

  - name: Tweak virtual memory 4/4
    ansible.posix.sysctl:
      name: vm.max_map_count
      value: '2097152'

  - name: Tweak file descriptors 1/2
    ansible.posix.sysctl:
      name: fs.file-max
      value: '2097152'

  - name: Tweak file descriptors 2/2
    ansible.posix.sysctl:
      name: fs.suid_dumpable
      value: '0'

  - name: Tweak network buffers 1/8
    ansible.posix.sysctl:
      name: net.core.wmem_default
      value: '25165824'

  - name: Tweak network buffers 2/8
    ansible.posix.sysctl:
      name: net.core.rmem_default
      value: '25165824'

  - name: Tweak network buffers 3/8
    ansible.posix.sysctl:
      name: net.core.wmem_max
      value: '25165824'

  - name: Tweak network buffers 4/8
    ansible.posix.sysctl:
      name: net.core.rmem_max
      value: '25165824'

  - name: Tweak network buffers 5/8
    ansible.posix.sysctl:
      name: net.ipv4.tcp_wmem
      value: '20480 12582912 25165824'

  - name: Tweak network buffers 6/8
    ansible.posix.sysctl:
      name: net.ipv4.tcp_rmem
      value: '20480 12582912 25165824'

  - name: Tweak network buffers 7/8
    ansible.posix.sysctl:
      name: net.ipv4.tcp_mem
      value: '65536 25165824 262144'

  - name: Tweak network buffers 8/8
    ansible.posix.sysctl:
      name: net.ipv4.udp_mem
      value: '65536 25165824 262144'

  - name: Enabling TCP window scaling
    ansible.posix.sysctl:
      name: net.ipv4.tcp_window_scaling
      value: '1'

  - name: Increase the value of net.ipv4.tcp_max_syn_backlog
    ansible.posix.sysctl:
      name: net.ipv4.tcp_max_syn_backlog
      value: '10240'

  - name: Increase the value of net.core.netdev_max_backlog
    ansible.posix.sysctl:
      name: net.core.netdev_max_backlog
      value: '65536'

  - name: Increase the maximum amount of option memory buffers
    ansible.posix.sysctl:
      name: net.core.optmem_max
      value: '25165824'

  - name: Number of times SYNACKs for passive TCP connection
    ansible.posix.sysctl:
      name: net.ipv4.tcp_synack_retries
      value: '2'

  - name: Allowed local port range
    ansible.posix.sysctl:
      name: net.ipv4.ip_local_port_range
      value: '2048 65535'

  - name: Protect Against TCP Time-Wait
    ansible.posix.sysctl:
      name: net.ipv4.tcp_rfc1337
      value: '1'

  - name: Decrease the time default value for tcp_fin_timeout connection
    ansible.posix.sysctl:
      name: net.ipv4.tcp_fin_timeout
      value: '15'

  - name: Set the maximum number of backlogged sockets
    ansible.posix.sysctl:
      name: net.core.somaxconn
      value: '4096'

  - name: Turn on syncookies for SYN flood attack protection
    ansible.posix.sysctl:
      name: net.ipv4.tcp_syncookies
      value: '1'

  - name: Avoid a smurf attack
    ansible.posix.sysctl:
      name: net.ipv4.icmp_echo_ignore_broadcasts
      value: '1'

  - name: Turn on protection for bad icmp error messages
    ansible.posix.sysctl:
      name: net.ipv4.icmp_ignore_bogus_error_responses
      value: '1'

  - name: Enable automatic window scaling
    ansible.posix.sysctl:
      name: net.ipv4.tcp_window_scaling
      value: '1'

  - name: Turn on and log spoofed, source routed, and redirect packets 1/2
    ansible.posix.sysctl:
      name: net.ipv4.conf.all.log_martians
      value: '1'

  - name: Turn on and log spoofed, source routed, and redirect packets 2/2
    ansible.posix.sysctl:
      name: net.ipv4.conf.default.log_martians
      value: '1'

  - name: Set max orphans
    ansible.posix.sysctl:
      name: net.ipv4.tcp_max_orphans
      value: '65536'

  - name: Do not cache metrics on closing connections
    ansible.posix.sysctl:
      name: net.ipv4.tcp_no_metrics_save
      value: '1'

  - name: Enable timestamps as defined in RFC1323
    ansible.posix.sysctl:
      name: net.ipv4.tcp_timestamps
      value: '1'

  - name: Enable select acknowledgments
    ansible.posix.sysctl:
      name: net.ipv4.tcp_sack
      value: '1'

  - name: Increase the tcp-time-wait buckets pool size 1/2
    ansible.posix.sysctl:
      name: net.ipv4.tcp_max_tw_buckets
      value: '1440000'

  - name: Increase the tcp-time-wait buckets pool size 2/2
    ansible.posix.sysctl:
      name: net.ipv4.tcp_tw_reuse
      value: '1'

  - name: Drop packets with the SSR or LSR option set 1/2
    ansible.posix.sysctl:
      name: net.ipv4.conf.all.accept_source_route
      value: '0'

  - name: Drop packets with the SSR or LSR option set 2/2
    ansible.posix.sysctl:
      name: net.ipv4.conf.default.accept_source_route
      value: '0'

  - name: Turn on reverse path filtering 1/2
    ansible.posix.sysctl:
      name: net.ipv4.conf.all.rp_filter
      value: '1'

  - name: Turn on reverse path filtering 2/2
    ansible.posix.sysctl:
      name: net.ipv4.conf.default.rp_filter
      value: '1'

  - name: Disable ICMP redirect acceptance 1/4
    ansible.posix.sysctl:
      name: net.ipv4.conf.all.accept_redirects
      value: '0'

  - name: Disable ICMP redirect acceptance 2/4
    ansible.posix.sysctl:
      name: net.ipv4.conf.default.accept_redirects
      value: '0'

  - name: Disable ICMP redirect acceptance 3/4
    ansible.posix.sysctl:
      name: net.ipv4.conf.all.secure_redirects
      value: '0'

  - name: Disable ICMP redirect acceptance 4/4
    ansible.posix.sysctl:
      name: net.ipv4.conf.default.secure_redirects
      value: '0'

  - name: Disables sending of all IPv4 ICMP redirected packets 1/2
    ansible.posix.sysctl:
      name: net.ipv4.conf.all.send_redirects
      value: '0'

  - name: Disables sending of all IPv4 ICMP redirected packets 2/2
    ansible.posix.sysctl:
      name: net.ipv4.conf.default.send_redirects
      value: '0'

  - name: Disable IP forwarding
    ansible.posix.sysctl:
      name: net.ipv4.ip_forward
      value: '0'

  - name: Disable IPv6 1/2
    ansible.posix.sysctl:
      name: net.ipv6.conf.all.disable_ipv6
      value: '1'

  - name: Disable IPv6 2/2
    ansible.posix.sysctl:
      name: net.ipv6.conf.default.disable_ipv6
      value: '1'

  - name: Tweak kernel parameters 1/2
    ansible.posix.sysctl:
      name: kernel.randomize_va_space
      value: '2'

  - name: Tweak kernel parameters 2/2
    ansible.posix.sysctl:
      name: kernel.pid_max
      value: '65536'

  - name: Reboot machine
    ansible.builtin.reboot:
